name: BlastFishing
main: org.kaufer.matthew.BlastFishing.BlastFishing
version: 1.0.0
author: mjkaufer
commands:
    blastfishing:
        description: returns plugin info
permissions:
    BlastFishing.use:
        description: allows users to blastfish
        default: true